name: neobis_smart_tailor
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # UI Style package
  flutter_svg: ^2.0.10+1
  flutter_gen: ^5.3.2
  cupertino_icons: ^1.0.2

  # Navigation Components
  auto_route: ^7.8.4

  # DI (Get It)
  get_it: ^7.7.0
  injectable: ^2.1.2

  # BLoC 
  flutter_bloc: ^8.1.5
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2

  # Remote
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1

  # Localization
  slang: 3.29.0
 
  # Utils
  flutter_native_splash: ^2.4.0 
  image_picker: ^1.1.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^7.3.2
  flutter_gen_runner:
  injectable_generator: ^2.4.1
  slang_build_runner: 3.29.0
  

  flutter_lints: ^2.0.0


flutter:
 uses-material-design: true

 assets:
   - assets/
   - assets/fonts/

 fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
       


  